---
- name: New user is created
  hosts: webservers
  become: true

  tasks:
    - name: User gets created
      include_vars:
        file: secret

    - name: Display the encrypted variable
      debug:
        msg: "{{ secret }}"

    - user:
        name: "{{ username['test']['uname'] }}"
        comment: "{{ username['test']['description'] }}"
        state: present
