---
- name: New user are created
  hosts: databases
  become: true

  tasks:
    - name: Create database users
      user:
        name: "{{ item }}"
        state: present
      loop: "{{ db_users }}"
